#                 _   _                     _     _                           Our plugins: https://alonsoaliaga.com/plugins
#                /_\ | |___ _ _  ___ ___ _ | |___(_)_ _                       Support server: https://alonsoaliaga.com/discord
#               / _ \| / _ \ ' \(_-</ _ \ || / _ \ | ' \                      Youtube: https://alonsoaliaga.com/play
#              /_/ \_\_\___/_||_/__/\___/\__/\___/_|_||_|                     Test server: plugins.alonsoaliaga.com
#                           by AlonsoAliaga                                   Twitch: https://alonsoaliaga.com/twitch
#        Considering donating? https://alonsoaliaga.com/donate                Thanks for downloading my plugin <3.
Messages:
  No-permission: "&cYou don't have permission to do this."
  Reloaded: "&aSome messages and options have been reloaded. Others may require a restart!"
  Invalid-player: "&cPlayer is not online!"
  Joined-in-silence: "&4✪ &eWelcome {PLAYER}, you just joined in silence. You won't be announced!"
  Help:
    Admin:
    - "&5 /alonsojoin testjoin <player> &f- &dTest join message for a player for you."
    - "&5 /alonsojoin testquit <player> &f- &dTest join message for a player for you."
    - "&5 /alonsojoin testhover <message> &f- &dTest a message in hover. (To test colors)"
    - "&5 /alonsojoin testexceptions &f- &dTest exceptions. (To test vanish plugins)"
    - "&5 /alonsojoin testaction <action> &f- &dTest an action. (Requires OP for some types)"
    - "&5 /alonsojoin testformat <identifier> &f- &dTest a format."
    - "&5 /alonsojoin broadcastjoin <player> [delay] &f- &dTest join message for a player for everyone."
    - "&5 /alonsojoin broadcastquit <player> &f- &dTest join message for a player for everyone."
    - "&5 /alonsojoin fakejoin <player> &f- &dBroadcast join message for everyone ignoring exceptions."
    - "&5 /alonsojoin fakeleave <player> &f- &dBroadcast quit message for everyone ignoring exceptions."
    - "&5 /alonsojoin reload &f- &dReload configuration (Restart recommended)"
    User: []
  Test-format:
    Invalid: "&cProvided identifier is not valid."
    Already-testing: "&cYou are already testing a format, wait some seconds.."
    Testing-join: "&aTesting join '{IDENTIFIER}' for '{PLAYER}'.."
    Testing-quit-delay: "&aTesting quit '{IDENTIFIER}' for '{PLAYER}' in 3 seconds.."
    Testing-quit: "&aTesting quit '{IDENTIFIER}' for '{PLAYER}'.."
  Test:
    Not-available: "&cThis player doesn't have any join message format available."
    Running-join: "&aRunning '{IDENTIFIER}' join format for {PLAYER}."
    Running-quit: "&aRunning '{IDENTIFIER}' quit format for {PLAYER}."
  Broadcast:
    Not-available: "&cThis player doesn't have any quit message format available."
    Running-join: "&aRunning '{IDENTIFIER}' join broadcast for {PLAYER}."
    Running-quit: "&aRunning '{IDENTIFIER}' quit broadcast for {PLAYER}."
  Test-exceptions:
    You-are-vanished: "&aYou are in vanish! You won't be announced on join."
    You-are-not-vanished: "&cYou are not in vanish! You will be announced on join."
    Target-is-vanished: "&aTarget is in vanish! Target won't be announced on join."
    Target-is-not-vanished: "&aTarget is not in vanish! Target will be announced on join."

Permissions:
  #Permission required to perform /alonsojoin command.
  #Set to "none" to not require permission.
  Main: "none" #Example: "alonsojoin.main"
  #Permissions below cannot be "none"
  Admin: "alonsojoin.admin"
  Fake-join: "alonsojoin.fake-join"
  Fake-leave: "alonsojoin.fake-leave"

Options:
  #Enable only if developer asks you to do it. It will spam console/chat with messages.
  Debug: false
  #Shouldn't be necessary. Leave it as false.
  Async-mode: false
  Command:
    Aliases:
    - "ajoin"
  #This option simply removes the default "AlonsoAliaga joined the server." from spigot.
  #It's really recommended to leave the enabled, unless you want to have two join messages.
  Remove-default: true
  #This is whitelist feature.
  #If enable, the message for the player who joined will only be sent to all players in the worlds in this list.
  #If disabled, message will be sent to all players in ALL WORLDS.
  Whitelist:
    Enabled: false
    Worlds:
    - "world"
    - "lobby"
  #Delay in ticks to send the message.
  #This feature was added in case you have plugins that load placeholders for PlaceholderAPI too late.
  #Time in ticks. 20 ticks = 1 second, 60 ticks = 3 seconds, 100 ticks = 5 seconds.
  #It's highly recommended to use a delay of 3 seconds. (By default)
  #Set to 0 or negative to disable delay.
  Delay: 60
  #This is a brand new feature that "adds compatibility" with vanished/staff-mode plugins
  Exceptions:
    #Enable this ONLY if you want this feature to work.
    #Make sure you also edit, add or remove the values you don't need.
    #Make sure you ONLY KEEP the values you need to not affect performance.
    Enabled: true
    #Notify the player who just joined that he wasn't announced because of vanish?
    #If "true" player will receive a message like "You joined on vanish and won't be announced!
    #If "false" player won't receive a message!
    Notify-player: true
    #This is the permission required to be able to recognized as "staff".
    #Only when players with THIS PERMISSION join the server the checks will be made.
    #You can algo give this permission to youtuber if you have a disguise plugin.
    Permission: "alonsojoin.staff"
    Metadatas:
    - "Vanished"
    - "vanished"
    Placeholders:
      #Make sure you ONLY enable the ONES YOU NEED.
      #If you don't have SuperVanish plugin, REMOVE THAT LINE line. DON'T SIMPLY CHANGE TO "false". REMOVE IT!!!!!!!!!!!
      #If the vanish plugin you use is not listed below, add the placeholder including %
      #and define the expected value so the player is recognized as vanished player.
      "%supervanish_isvanished%": "true"
      "%premiumvanish_isvanished%": "true"
      "%stafffacilities_vanished%": "true"
      "%protocolvanish_player_is_vanished%": "true"
      "%essentials_vanished%": "yes"
    Hooks:
      #Hooks with AuthMe plugin to announce only when player has successfully logged in.
      AuthMe:
        Enabled: true
        #If enabled, using /logout and /login will NOT spam connection message.
        #This adds a metadata to the player so CONNECTING again is always required to send the message.
        Prevent-spam: true
    #Allow players to ignore damage from Fireworks. If enabled players will RECEIVE fireworks damage.
    #Keep this disabled.
    Firework-damage: false
  Colors:
    #This is an attempt to make hex color look as close as possible to minecraft native colors for 1.8 - 1.15 players.
    Fix: true
  Placeholders:
    #This is ONLY USED FOR %alonsojoin_restorehex_ANOTHERPLACECHOLDER%
    #Do NOT modify if you don't know what it does.
    Hex-format: "&#{COLOR}"

Updates:
  #Auto update configuration? Enabling will delete comments.
  Auto-update-configuration: true
  #Check for updates? Recommended to keep it enabled.
  Check-updates: true
  #Notify updates when player with permission joins the server?
  Notify-updates: true
  #Permission required to receive update message.
  Permission: "alonsojoin.update"
  #Message to send when update is found.
  Message: "&5[AlonsoJoin] &eA new update has been found! You are using version {CURRENT}. Download version {NEW} here &c{LINK}"
